### ISSUE TITLE
【车辆调度工具】不关联配车计划，只有物流计划，没有触发物流计划的已配车运量的计算

### ISSUE THREAD

**Issue by goodgoodlooklook** [ZhangLianK/shipping_management#10]

**Comment by emzhou** [comment]
问题描述：不关联配车计划，只有物流计划，没有触发物流计划的已配车运量的计算

**Comment by emzhou** [comment]
ZhangLianK：已配车运量的计算有一个function，这个function应该在配车计划的py文件中
在Scale Item中，import这个function，然后在对应event的地方把这个加一下，应该是在on_update_after_submit, on_submit 的位置；除了改这些，还得把这个function也改了，这个function中只统计了一配车计划的量，没有统计配车计划是空，但是有物流计划的 scale item；先在本地跑通

**Comment by emzhou** [comment]
物流计划已配车运量计算问题已解决

**Comment by emzhou** [comment]
目前物流计划已配车运量问题已经解决
