### ISSUE TITLE
物流单从 外卖销售订单 改到入库的时候，需要把订单备注清掉

### ISSUE THREAD

**Issue by ZhangLianK** [ZhangLianK/shipping_management#55]

**Comment by emzhou** [comment]
从外卖类型改到入库后，关联信息里的订单备注已经清掉，但计量单描述信息最后一段订单备注没有清掉
![1712709181872](https://github.com/ZhangLianK/shipping_management/assets/152852316/8f74baea-1206-4769-8d65-ba427fa01c2e)
