### ISSUE TITLE
物流计量单报表执行报错

### ISSUE THREAD

**Issue by ZhangLianK** [ZhangLianK/shipping_management#7]
from `tabScale Item`  sci
        left outer join vehicle_plan_item vpi
            on sci.vehicle_plan = vpi.name
        left outer join `tabDriver` d
            on sci.driver = d.name
        left outer join `tabShip Type` s
            on sci.type = s.name
        left outer join `tabScale Type` i
            on sci.bill_type = i.name

**Comment by goodgoodlooklook** [comment]
fixed,merge to test
